### ISSUE TITLE
Migration to Bridge

### ISSUE THREAD

**Issue by TinkerWorX** [bridgedotnet/Granular#25]
What would need to be changed to use Granular with [Bridge](https://github.com/bridgedotnet/Bridge)?

**Comment by yuvaltz** [comment]
Currently Bridge doesn't support reflection and embedded resources which are supported in Saltarelle
Bridge 2.0 is promised to have some of Saltarelle's capabilities (I know that reflection is there, not sure about resources, and I couldn't find the planned features list)
I'm looking forward for Bridge 2.0, it supposed to have great performance (which is critical for Granular), so as soon as it'll be released I'll start testing it

**Comment by TinkerWorX** [comment]
Ah, so there are still some technical limitations. It's good to hear that you're still actively going to update.

**Comment by vladsch** [comment]
Bridge 15.1 supports reflection and embedded resources now
You can test it in Deck application
http://deck.net/c2009cd4e1ae83146264c482cb5fe6cf

**Comment by yuvaltz** [comment]
Yes, I've seen it a couple of days ago, I'm very excited about it and already started playing with it.
You guys really did an amazing job!

**Comment by geoffreymcgill** [comment]
**Granular** has completed it's migration to Bridge. 

https://github.com/bridgedotnet/Granular
